<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: April 20th at 2:14pm
 */
namespace OpenFood\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class CompanySchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'name',
  1 => 'address',
  2 => 'phone',
  3 => 'fax',
  4 => 'principal',
  5 => 'principal_phone',
  6 => 'locale',
  7 => 'id',
);
    public static $column_hash = array (
  'name' => 1,
  'address' => 1,
  'phone' => 1,
  'fax' => 1,
  'principal' => 1,
  'principal_phone' => 1,
  'locale' => 1,
  'id' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'name',
  1 => 'address',
  2 => 'phone',
  3 => 'fax',
  4 => 'principal',
  5 => 'principal_phone',
  6 => 'locale',
  7 => 'id',
);

    const schema_class = 'OpenFood\\Model\\CompanySchema';
    const collection_class = 'OpenFood\\Model\\CompanyCollection';
    const model_class = 'OpenFood\\Model\\Company';
    const model_name = 'Company';
    const model_namespace = 'OpenFood\\Model';
    const primary_key = 'id';
    const table = 'companies';
    const label = 'Company';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'name' => array( 
      'name' => 'name',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 60,
        ),
    ),
  'address' => array( 
      'name' => 'address',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 120,
        ),
    ),
  'phone' => array( 
      'name' => 'phone',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 20,
        ),
    ),
  'fax' => array( 
      'name' => 'fax',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 20,
        ),
    ),
  'principal' => array( 
      'name' => 'principal',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 30,
        ),
    ),
  'principal_phone' => array( 
      'name' => 'principal_phone',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 20,
        ),
    ),
  'locale' => array( 
      'name' => 'locale',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 12,
          'validValues' => array( 
              'en',
              'zh_TW',
            ),
        ),
    ),
  'id' => array( 
      'name' => 'id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => true,
          'autoIncrement' => true,
        ),
    ),
);
        $this->columnNames     = array( 
  'id',
  'name',
  'address',
  'phone',
  'fax',
  'principal',
  'principal_phone',
  'locale',
);
        $this->primaryKey      = 'id';
        $this->table           = 'companies';
        $this->modelClass      = 'OpenFood\\Model\\Company';
        $this->collectionClass = 'OpenFood\\Model\\CompanyCollection';
        $this->label           = 'Company';
        $this->relations       = array( 
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('Company');
    }

}
