<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: April 20th at 12:08pm
 */
namespace OpenFood\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class FoodSchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'name',
  1 => 'company_id',
  2 => 'updated_at',
  3 => 'created_at',
  4 => 'id',
);
    public static $column_hash = array (
  'name' => 1,
  'company_id' => 1,
  'updated_at' => 1,
  'created_at' => 1,
  'id' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'name',
  1 => 'company_id',
  2 => 'updated_at',
  3 => 'created_at',
  4 => 'id',
);

    const schema_class = 'OpenFood\\Model\\FoodSchema';
    const collection_class = 'OpenFood\\Model\\FoodCollection';
    const model_class = 'OpenFood\\Model\\Food';
    const model_name = 'Food';
    const model_namespace = 'OpenFood\\Model';
    const primary_key = 'id';
    const table = 'foods';
    const label = 'Food';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'name' => array( 
      'name' => 'name',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 60,
        ),
    ),
  'company_id' => array( 
      'name' => 'company_id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => NULL,
        ),
    ),
  'updated_at' => array( 
      'name' => 'updated_at',
      'attributes' => array( 
          'isa' => 'DateTime',
          'type' => 'datetime',
          'primary' => NULL,
          'timezone' => true,
        ),
    ),
  'created_at' => array( 
      'name' => 'created_at',
      'attributes' => array( 
          'isa' => 'DateTime',
          'type' => 'datetime',
          'primary' => NULL,
          'timezone' => true,
        ),
    ),
  'id' => array( 
      'name' => 'id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => true,
          'autoIncrement' => true,
        ),
    ),
);
        $this->columnNames     = array( 
  'id',
  'name',
  'company_id',
  'updated_at',
  'created_at',
);
        $this->primaryKey      = 'id';
        $this->table           = 'foods';
        $this->modelClass      = 'OpenFood\\Model\\Food';
        $this->collectionClass = 'OpenFood\\Model\\FoodCollection';
        $this->label           = 'Food';
        $this->relations       = array( 
  'company' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 3,
      'self_schema' => 'OpenFood\\Model\\FoodSchema',
      'self_column' => 'company_id',
      'foreign_schema' => 'OpenFood\\Model\\CompanySchema',
      'foreign_column' => 'id',
    ),
  'accessor' => 'company',
  'where' => NULL,
  'orderBy' => array( 
    ),
)),
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('Food');
    }

}
